### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/ppc-wallet#3]
We need internationalization in order to get more users.

**Comment by jointhepartypooper** [comment]
I am not familiar with brunch. How is i18n done preferably in brunch?

**Comment by kazzkiq** [comment]
Issue fixed.

The default behavior to detect user language is:
1. Check if user has a `ppc-user-language` key in localStorage (useful if user wants to force another language instead of using its browser's default);
2. If don't, use `navigator.language` to detect language;
3. If that fails, defaults to `en-US`.

i18n files are located at `app/assets/locales`.

i18n files must have the same name as the language/country code. e.g. `en-US`, `pt-BR`, `hr-HR`, etc.

An example can be found [here](https://github.com/peercoin/peercoin-address-generator/blob/master/app/assets/locales/en-US.json).
